services:
  - type: web
    name: kingbot-ultra
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: BOT_TOKEN
        value: 8692584207:AAFlXH1Rt2z4vLWLvgQySwj33dV20LqGk3k
      - key: ADMIN_PASSWORD
        value: admin123
      - key: SHOP_NAME
        value: KingBot Luxury
      - key: GROUP_CHAT_ID
        sync: false
